routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::post('/posts/{post}/comment', [App\Http\Controllers\PostController::class, 'comment'])->name('posts.comment');
Route::resource('/posts', App\Http\Controllers\PostController::class)->except(['index']);
Route::get('/profile', [App\Http\Controllers\UserController::class, 'edit'])->name('profile.edit')->middleware('auth');
Route::put('/profile', [App\Http\Controllers\UserController::class, 'update'])->name('profile.update')->middleware('auth');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
}

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = ['user_id', 'text'];
    protected $with = ['user'];
    public function commentable(){
        return $this->morphTo();
    }
    public function comments(){
        return $this->morphMany(Comment::class, 'commentable')->orderBy('created_at');
    }
    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
    protected $fillable = ['name', 'text'];
    public function comments(){
        return $this->morphMany(Comment::class, 'commentable')->latest();
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CategoryController extends Controller
{
    //
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CommentController extends Controller
{
    //
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Post;
class HomeController extends Controller
{
    public function index(Request $request) {
        $posts = Post::latest();
        $q = $request->q;
        if($q) $posts = $posts->where('name', 'like', "%$q%")->orWhere('text', 'like', "%$q%");
        $posts = $posts->paginate(5);
        return view('home', compact('posts', 'q'));
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Post;
class PostController extends Controller
{
    public function __construct(){
        $this->middleware(['auth', 'admin'])->except(['show', 'comment']);
        $this->middleware('auth')->only('comment');
    }
    public function create(){
        return view('posts.create');
    }
    public function edit(Post $post){
        return view('posts.update', compact('post'));
    }
    public function show(Post $post){
        $post->load('comments');
        return view('posts.show', compact('post'));
    }
    public function store(Request $request){
        $request->validate([
            'name' => 'required|string|max:255',
            'text' => 'required'
        ]);
        Post::create($request->only([
            'name',
            'text'
        ]));
        session()->flash('message', 'Новая запись успешно добавлена');
        return redirect()->route('home');
    }
    public function update(Request $request, Post $post){
        $request->validate([
            'name' => 'required|string|max:255',
            'text' => 'required'
        ]);
        $post->update($request->only([
            'name',
            'text'
        ]));
        session()->flash('message', 'Запись успешно изменена');
        return redirect()->route('home');
    }
    public function destroy(Post $post){
        $post->delete();
        session()->flash('message', 'Запись успешно удалена');
        return redirect()->route('home');
    }
    public function comment(Request $request, Post $post){
        $request->validate([
            'text' => 'required'
        ]);
        $data = $request->only('text');
        $data['user_id'] = auth()->id();
        $post->comments()->create($data);
        return back();
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
class UserController extends Controller
{
    public function edit(){
        $user = auth()->user();
        return view('users.edit', compact('user'));
    }
    public function update(Request $request){
        $user = auth()->user();
        $request->validate([
            'password' => 'required|confirmed|string|max:255|min:6'
        ]);
        $password = bcrypt($request->password);
        $user->update([
            'password' => $password
        ]);
        session()->flash('message', 'Пароль успешно изменен');
        return redirect()->route('users.edit');
    }
}

resources/views/home.blade.php
@extends('layouts.site')

@section('content')
@if($posts->count())
    @foreach($posts as $post)
    <div class="blog-post">
        <h2 class="blog-post-title"><a href="{{route('posts.show', $post->id)}}" class="text-reset">{{$post->name}}</a></h2>
        @if(auth()->check() && auth()->user()->admin)
            <a href="{{route('posts.edit', $post->id)}}" class="text-warning small mr-2">Редактировать</a>
            <form action="{{route('posts.destroy', $post->id)}}" class="confirmed d-inline-block" method="post">
                @csrf
                <input type="hidden" name="_method" value="DELETE">
                <button class="btn btn-link text-danger">Удалить</button>
            </form>
        @endif
        <p class="blog-post-meta small">{{$post->created_at->format('d.m.Y H:i')}}</p>
        {!!mb_strimwidth($post->text, 0, 150, '...')!!} <a href="{{route('posts.show', $post->id)}}">Читать далее</a>
    </div>
    <hr>
    @endforeach
    {{$posts->links('vendor.pagination.bootstrap-4')}}
@else
    <h5>В блоге пока нет ни одной записи</h5>
@endif
@stop

resources/views/layouts/site.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title', 'Блог')</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <div class="container">
			<header class="blog-header py-3">
				<div class="row flex-nowrap justify-content-between align-items-center">
				<div class="col-4 pt-1"></div>
				<div class="col-4 text-center">
					<a class="blog-header-logo text-dark" href="{{route('home')}}">Блог</a>
				</div>
				<div class="col-4 d-flex justify-content-end align-items-center">
					<form action="{{route('home')}}" class="d-inline-block mr-3">
						<div class="input-group input-group-sm">
							<input type="text" class="form-control form-control-sm" name="q" placeholder="Поиск..." @if(isset($q)) value="{{$q}}" @endif>
							<div class="input-group-append">
								<div class="input-group-text px-1">
									<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24" focusable="false"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"></circle><path d="M21 21l-5.2-5.2"></path></svg>
								</div>
							</div>
						</div>
					</form>
					@guest
					<a class="btn btn-sm btn-outline-secondary" href="{{route('login')}}">Вход</a>
					@else
					<form action="{{route('logout')}}" method="post">
						@csrf
						<button class="btn btn-outline-secondary btn-sm btn-block">Выход</button>
					</form>
					@endguest
				</div>
				</div>
			</header>
  
			<main role="main" class="mt-5">
				<div class="row">
					<div class="col-md-8 blog-main">
						@if(session()->has('message'))
							<div class="alert alert-info">{{session('message')}}</div>
						@endif
						@yield('content')
					</div><!-- /.blog-main -->

					<aside class="col-md-4 blog-sidebar">
						@if(auth()->check() && auth()->user()->admin)
						<div class="px-4 mb-3">
							<a href="{{route('posts.create')}}" class="btn btn-sm btn-block btn-outline-secondary mb-3">Добавить запись</a>
							<hr>
							<a href="{{route('profile.edit')}}" class="btn btn-sm btn-block btn-outline-secondary mb-3">Сменить пароль</a>
						</div>
						@endif
						<div class="px-4 mb-3">
							
						</div>
						<div class="px-4">
							<h4 class="font-italic">Соц сети</h4>
							<ol class="list-unstyled">
							<li><a href="#">GitHub</a></li>
							<li><a href="#">Twitter</a></li>
							<li><a href="#">Facebook</a></li>
							</ol>
						</div>
					</aside><!-- /.blog-sidebar -->

				</div><!-- /.row -->

			</main>
			<footer class="blog-footer mt-5">
				<p><a class="text-secondary" href="#">В начало</a></p>
			</footer>
		</div>
	</div>
</body>
</html>

resources/views/posts/create.blade.php
@extends('layouts.site')

@section('content')
    <form action="{{route('posts.store')}}" method="post">
        @csrf
        @if($errors->count())
            <div class="alert alert-danger">
                <ul>
                @foreach($errors->all() as $error)
                <li>{{$error}}</li>
                @endforeach
                </ul>
            </div>
        @endif
        <div class="form-group">
            <label>Заголовок</label>
            <input type="text" class="form-control" name="name" value="{{old('name')}}">
        </div>
        <div class="form-group">
            <label>Текст</label>
            <textarea name="text" rows="10" class="form-control">{{old('text')}}</textarea>
        </div>
        <div class="form-group">
            <button class="btn btn-outline-secondary">Сохранить</button>
        </div>
    </form>
@stop

resources/views/posts/show.blade.php
@extends('layouts.site')

@section('title')
{{$post->name}}
@stop

@section('content')
<h1>{{$post->name}}</h1>
<small class="text-muted">{{$post->created_at->format('d.m.y H:i')}}</small>
@if(auth()->check() && auth()->user()->admin)
    <a href="{{route('posts.edit', $post->id)}}" class="text-warning small mr-2">Редактировать</a>
    <form action="{{route('posts.destroy', $post->id)}}" class="confirmed d-inline-block" method="post">
        @csrf
        <input type="hidden" name="_method" value="DELETE">
        <button class="btn btn-link text-danger">Удалить</button>
    </form>
@endif
<hr>
{!!$post->text!!}
<hr>
<h4>Комментарии <big class="text-info">{{$post->comments->count()}}</big></h4>
@foreach($post->comments as $comment)
<div class="media text-muted pt-3">
    <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"></rect><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
    <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
    <strong class="d-block text-gray-dark">@ {{$comment->user->name}} <small>{{$comment->created_at->format('d.m.Y H:i')}}</small></strong>
    {{$comment->text}}
    </p>
</div>
@endforeach
@guest
<a href="{{route('login')}}">Авторизуйтесь, чтобы оставлять комментарии</a>
@else
<form action="{{route('posts.comment', $post->id)}}" method="post">
    @csrf
    <div class="form-group">
        <label>Ваш комментарий</label>
        <textarea name="text" rows="3" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <button class="btn btn-outline-secondary btn-sm">Отправить</button>
    </div>
</form>
@endguest

@stop

resources/views/posts/update.blade.php
@extends('layouts.site')

@section('content')
    <form action="{{route('posts.update', $post->id)}}" method="post">
        @csrf
        <input type="hidden" name="_method" value="PUT">
        <div class="form-group">
            <label>Заголовок</label>
            <input type="text" class="form-control" name="name" value="{{old('name') ? old('name') : $post->name}}">
            @error('name')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
        <div class="form-group">
            <label>Текст</label>
            <textarea name="text" rows="10" class="form-control">{{old('text') ? old('text') : $post->text}}</textarea>
            @error('text')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
        <div class="form-group">
            <button class="btn btn-outline-secondary">Сохранить</button>
        </div>
    </form>
@stop

resources/views/users/edit.blade.php
@extends('layouts.site')

@section('content')
<form action="{{route('profile.update')}}" method="post">
    @csrf
    <input type="hidden" name="_method" value="PUT">
    @if($errors->count())
        <div class="alert alert-danger">
            <ul>
            @foreach($errors->all() as $error)
            <li>{{$error}}</li>
            @endforeach
            </ul>
        </div>
    @endif
    <div class="form-group">
        <label>Новый пароль</label>
        <input type="password" name="password" class="form-control">
    </div>
    <div class="form-group">
        <label>Подтвердите пароль</label>
        <input type="password" name="password_confirmation" class="form-control">
    </div>
    <div class="form-group">
        <button class="btn btn-outline-secondary">Сохранить</button>
    </div>
</form>
@stop